name: Daily Mood Update

on:
  schedule:
    - cron: "0 16 * * *"

jobs:
  update_message:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run update script
        run: chmod +x daily_mood.sh && ./daily_mood.sh